steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-south1-docker.pkg.dev/reference-bee-410205/weber-repo/weber:$COMMIT_SHA'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/reference-bee-410205/weber-repo/weber:$COMMIT_SHA'

- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
    - run
    - --filename=deployment.yaml
    - --image=asia-south1-docker.pkg.dev/reference-bee-410205/weber-repo/weber:$COMMIT_SHA
    - --cluster=weber-cluster
    - --location=asia-south1
